@million.api_HostAddress = http://localhost:5005

GET {{ million.api_HostAddress}}/api/property/filter?minPrice=12000000&maxPrice=15000000
Accept: application/json



###
POST  {{ million.api_HostAddress }}/api/property
Content-Type: application/json
Accept: application/json

{
  "ownerId":"68b0c95f2b0f2e5e988f55f4",
  "name": "Cali ",
  "address": "sucursal del cielo",
  "price": 1400,
  "codeInternal": "111",
  "year": "2020"
}


###
POST  {{ million.api_HostAddress }}/api/owner
Content-Type: application/json
Accept: application/json

{
  "name": "Juan David",
  "address": "calle melendez",
  "birtday": "02-09-1996",
  "photo": "999"
}


###

POST  {{ million.api_HostAddress }}/api/property/createdPropertyImg
Content-Type: application/json
Accept: application/json

{
  "propertyId": "68b1ee10e344a9bbbf767f16",
  "file": "melendez tour"
}

###
POST  {{ million.api_HostAddress }}/api/property/createdPropertyTrace
Content-Type: application/json
Accept: application/json

{
  "propertyId": "68b0cac487382bcef4797eba",
  "name": " melendez 2",
  "value": "value 2",
  "dateSale":"2025-08-28T10:15:00",
  "tax": 1.5
}
