@million.api_HostAddress = http://localhost:5005

GET {{ million.api_HostAddress}}/api/property/filter
Accept: application/json

###
GET {{ million.api_HostAddress}}/api/property/68b25a3c1b19a9a834c26ca6
Accept: application/json



###
POST  {{ million.api_HostAddress }}/api/property
Content-Type: application/json
Accept: application/json

{
  "ownerId":"68b25395d967c420c94e14e2",
  "name": "apto 201 rocki Céntrico",
  "address": "Calle medio 15, Madrid, 28013",
  "price": 340000000,
  "codeInternal": "PROP-003",
  "year": "2022"
}


###
POST  {{ million.api_HostAddress }}/api/owner
Content-Type: application/json
Accept: application/json

{
  "name": "Joel Vaquero-Almagro",
  "address": "Av. de los Olivos 45, Sevilla, España",
  "birtday": "1996-09-02",
  "photo": "https://avatar.iran.liara.run/public/44"
}


###

POST  {{ million.api_HostAddress }}/api/property/createdPropertyImg
Content-Type: application/json
Accept: application/json

{
  "propertyId": "68b28473c45ed1af239e146d",
  "file": "https://images.unsplash.com/photo-1565145211217-d0f630de0004?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3OTgzMjZ8MHwxfHNlYXJjaHwyfHxob3VzZSUyMGZhY2FkZXxlbnwwfHx8fDE3NTY1MTgyNTN8MA&ixlib=rb-4.1.0&q=85"
}

###
POST  {{ million.api_HostAddress }}/api/property/createdPropertyTrace
Content-Type: application/json
Accept: application/json

{
  "propertyId": "68b25a3c1b19a9a834c26ca6",
  "name": "Venta en espera",
  "value": "Venta en espera",
  "dateSale":"2022-06-01T10:20:30",
  "tax": 1.6
}


###
POST  {{ million.api_HostAddress }}/api/property/createPropertyDetail
Content-Type: application/json
Accept: application/json

{
  "propertyId": "68b25a3c1b19a9a834c26ca6",
  "bedrooms": 4,
  "bathrooms": 3,
  "areaM2": 145,
  "garage": true,
  "yearBuilt": 2005,
  "description": "Casa moderna con jardín y piscina."
}
